### PR TITLE
add a default theme

### PR DESCRIPTION
**Pull request by michaelneale**
I have a history of terrible ideas and this is one of them, but bear with me. 
I noted that the material design theme was popular, and thought "what if this was the default for the simple theme plugin". 

I took the CSS from `https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-grey.css and added it to the resources, which are then loaded (locally, from the classpath). Should no elements/style components be configured, it will serve up that for the header HTML style.

(also tests added to check it can be overridden etc). 

I have an ulterior motive for this too: get this plugin included in the recommended set (that is a whole other proposal for later) as I think it is great (and works well, and people can remove/tweak). In this case it will need to have a default. 

In any case - may be a terrible idea but I enjoyed the pretty nice code in this plugin.

### CODE REVIEW

**Comment by michaelneale** [comment]
(I think those failures are unrelated - not sure how to kick off a rebuild on that infra).

**Comment by TobiX** [comment]
I'm a little bit conflicted about this :confused: 

1. I think this has some merit - I really like to make it easier for users to select a theme...
2. Since I maintain a theme myself, I'm quite torn between staying neutral, picking something which seems popular and picking my own theme :wink: 
3. Something similar could probably be achieved by creating a new `ThemeElement` to select from a list of packaged themes...
4. I'm hesitant to add third-party themes, which I (maybe) have to update regularly, so maybe some kind of auto-update would be nice?

**Comment by michaelneale** [comment]
@TobiX heh yeah I totally understand. If we look at the bigger aim - having the ability to have a new default theme is nice. Material is popular but perhaps yours is nicer? 

Autoupdate is a great idea - if the theme is maintained outside. Do you mean part of build time or runtime? 

I like the ThemeElement idea - but the killer for me is that there is a default (so one day this can be recommended!)

**Comment by michaelneale** [comment]
@TobiX what is your theme - could make it the default (and I like the idea of bundling them in too but my real aim is something else here...)

**Comment by TobiX** [comment]
My theme is the Neo2 theme: https://tobix.github.io/jenkins-neo2-theme/ (sample: https://buildbox.23.gs/jenkins/view/All/)

**Comment by michaelneale** [comment]
Oh I like that - a few "old" icons are still in use (maybe doesn't cover the full set) was only thing I noticed that I didn't like (maybe that happens with material too, but I didn't notice it when I tried).

**Comment by michaelneale** [comment]
hey @TobiX had any more thoughts about this?

**Comment by michaelneale** [comment]
@TobiX  - made neo2 the default as it seems better suited by the default (and made by you).

**Comment by TobiX** [comment]
Closing, because https://plugins.jenkins.io/theme-manager/ exists now, which provides a much better feature-set for "theme management"

**Pull request closed without merging**
