### PR TITLE
Add safe url to support relative address

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@TobiX Could you please help me to review these changes? Thanks.

**Comment by TobiX** [comment]
NACK. AFAICS this breaks the usecase when Jenkins and a bunch of resources are hosted on different paths on the same host. I currently have something like this:

Jenkins: http://internalweb.example.bogus/jenkins/
Resources: http://internalweb.example.bogus/css/company.css

Now I can use `/css/company.css`, which works without a problem. Do you have a different usecase?

**Comment by LinuxSuRen** [comment]
In my case, I wish I could host CSS files in my plugin. So I can use `/plugin/sample-plugin/company.css`

**Comment by LinuxSuRen** [comment]
I wonder if `http://internalweb.example.bogus` is another web server, maybe you can setting the CSS address as full url.

**Comment by TobiX** [comment]
After some more consideration, I'm going to reject this: This changes the semantic of URLs starting with a slash, so this would break installations currently using URLs in that format.

If you want to add a plugin containing a theme, you can extend the list of available theme elements like this:
```java
public class MyThemeElement extends ThemeElement {

  private static final String CSS_HTML =
      "<link type=\"text/css\" rel=\"stylesheet\" href=\"{0}/plugin/sample-plugin/company.css\"/>";

  @DataBoundConstructor
  public MyThemeElement() {
    super();
  }

  @Override
  public void collectHeaderFragment(Set<String> fragments, boolean injectCss) {
    String context = Stapler.getCurrentRequest().getContextPath();
    fragments.add(MessageFormat.format(CSS_HTML, context));
  }

  @Extension
  @Symbol("myTheme")
  public static final class DescriptorImpl extends Descriptor<ThemeElement> {

    @Override
    public String getDisplayName() {
      return "My Theme";
    }
  }
}
```

**Comment by LinuxSuRen** [comment]
I understand your concern. It's right. How about using a variable to change the semantic. eg: `${jenkins}` equals to `http://localhost:8080/jenkins`.

**Pull request closed without merging**
