### PR TITLE
Initial theme manager

### PR DESCRIPTION
**Pull request by timja**
Quite similar to: https://github.com/jenkinsci/simple-theme-plugin/pull/7

Allows themes to be registered through an extension point

Features:

* global theme
* user theme
* block users from being able to change their theme (not sure why but @oleg-nenashev asked for it)

Downstream plugin PR: https://github.com/jenkinsci/dark-theme/pull/77

Todo:

* ~extract themes to plugins~ - done for dark mode, probably all I will do
* ~serve resources from plugin instead of CDN~ - done, both modes are supported
* ~login theme integration~
* ~docs~ - done
* ~tests~ - jcasc tests are in

Thoughts?

cc @oleg-nenashev @TobiX @michaelneale

### CODE REVIEW

**Comment by michaelneale** [comment]
I like this idea, and this could replace whatn #7 does, perhaps (the idea was to ship with a default plugin so as soon as you install this, it looks different, but this seems more generally useful).

**Comment by daniel-beck** [comment]
Is there a reason this is part of simple-theme-plugin and not a new library plugin? There seems to be absolutely no overlap other than the general topic.

Going with a different structure of components would also allow to open up theme configuration to Overall/Manage users without allowing them to insert XSS code into Jenkins pages (which is pretty much inherent to simple-theme-plugin).

**Comment by timja** [comment]
I initially had it as a separate plugin, Oleg suggested in gitter we may not need a separate plugin and to put it here

No real opinion either way from myself.

**Comment by timja** [comment]
I think this could be opened up to manage anyway? It’s not the whole plugin right just this decorator?

**Comment by daniel-beck** [comment]
IMO it seems like a cleaner separation to split this off given this has absolutely no overlap. Less stuff to install, as it's not like you'd need both plugins anyway.

**Comment by timja** [comment]
> IMO it seems like a cleaner separation to split this off given this has absolutely no overlap. Less stuff to install, as it's not like you'd need both plugins anyway.

Sounds fine to me, I'll bring it up in the ux-sig meeting on Wednesday, (added to the agenda now)

**Comment by TobiX** [comment]
While I like the idea, I'm with @daniel-beck here: Let's make it it's own plugin (maybe "theme-manager" or "user-themes"?) - We can put a link in the documentation of "simple-theme" to promote the new plugin later.

**Comment by timja** [comment]
https://issues.jenkins-ci.org/browse/HOSTING-981

**Comment by TobiX** [comment]
Closed based on previous discussion

**Pull request closed without merging**
