### PR TITLE
Support for configuration-as-code plugin

### PR DESCRIPTION
**Pull request by jmsizun**
Support for configuration-as-code plugin (https://github.com/jenkinsci/configuration-as-code-plugin) (in  section unclassified/simple-theme-plugin)

### CODE REVIEW

**Comment by TobiX** [comment]
Thanks!

**Comment by minitux** [comment]
Hello, 
Is it possible to make a new release version with this feature ? 
Thanks

**Comment by ooxi** [comment]
I would really love if you could do a release containing this patch. Otherwise the demo, which is part of [configuration as code](https://github.com/jenkinsci/configuration-as-code-plugin/pull/261) does not work and might confuse new users (like myself).

**Comment by TobiX** [comment]
Sorry, release is now out. Be aware that the syntax has changed a bit: https://github.com/jenkinsci/simple-theme-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/simpletheme/ConfigurationAsCode.yml

**Comment by ooxi** [comment]
Thank you very much!

**Comment by minitux** [comment]
Works great ! Thanks

**Pull request merged**
